### ISSUE TITLE
Question about No module named 'recbole.data.dataset'

### ISSUE THREAD

**Issue by foureye** [juyongjiang/AdaMCT#1]
Traceback (most recent call last):
  File "run_recbole.py", line 48, in <module>
    run_recbole(
  File "/root/AdaMCT-master/recbole/quick_start/quick_start.py", line 70, in run_recbole
    dataset = create_dataset(config)
  File "/root/AdaMCT-master/recbole/data/utils.py", line 40, in create_dataset
    dataset_module = importlib.import_module("recbole.data.dataset")
  File "/root/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'recbole.data.dataset'

I check the path ,there is no dataset document in AdaMCT source code,but in original recbole ,there has this document。Need I to redownload recbole?
Thank you!

**Comment by LronKingGGB** [comment]
"Remove the 'recoble' package from the source code, install the official 'recoble' package using conda, then run the code again, and install any missing packages according to the error messages."
